// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shopAPI.Data;

#nullable disable

namespace shopAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240402085521_AddAdminTable")]
    partial class AddAdminTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shopAPI.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoginId = "admin",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("shopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8264),
                            ProductDescription = "haha",
                            ProductImage = "image",
                            ProductName = "yuri",
                            ProductPrice = 1000m,
                            UpdateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8274)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8276),
                            ProductDescription = "haha",
                            ProductImage = "image",
                            ProductName = "second",
                            ProductPrice = 2000m,
                            UpdateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8276)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8278),
                            ProductDescription = "haha",
                            ProductImage = "image",
                            ProductName = "third",
                            ProductPrice = 3000m,
                            UpdateAt = new DateTime(2024, 4, 2, 15, 55, 21, 141, DateTimeKind.Local).AddTicks(8278)
                        });
                });

            modelBuilder.Entity("shopAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
